sudo: false
language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache

install:
  - if [[ "$COMPOSER_FLAGS" == *"--prefer-lowest"* ]]; then travis_retry composer update --prefer-dist --prefer-stable --quiet; fi
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - ./vendor/bin/phpcs --standard=PSR2 ./src/
  - ./vendor/bin/phpcs --standard=PSR2 ./tests/

after_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" != 'hhvm-3.24' && "$TRAVIS_PHP_VERSION" != '7.0' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi

matrix:
  allow_failures:
    - php: hhvm

notifications:
  email: false
